version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Type: Dependencies :arrow_up:"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Type: Dependencies :arrow_up:"
  - package-ecosystem: "devcontainers"
    directory: "/.github/"
    schedule:
      interval: "weekly"
    labels:
      - "Type: Dependencies :arrow_up:"
