renv::init(bare = TRUE, force = TRUE)
renv::snapshot(lockfile = "inst/setup/renv.lock", packages = ".", force = TRUE)
unlink(".Rprofile")
unlink("renv", recursive = TRUE)
renv::record("renv@0.15.2", lockfile = "inst/setup/renv.lock")
