name: Build Docker

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        run: |
          if [[ "${{github.ref_name}}" = "main" ]]; then
            TAG="devel"
          else
            TAG="${{github.ref_name}}"
          fi
        
          docker buildx build \
            --push \
            --platform "linux/amd64" \
            --label "org.opencontainers.image.title": "eggla",
            --label "org.opencontainers.image.description": "Docker image for the 'eggla' R package.",
            --label "org.opencontainers.image.base.name": "docker.io/mcanouil/r-ver:4.2.0"
            --label "org.opencontainers.image.source=https://github.com/mcanouil/eggla" \
            --label "org.opencontainers.image.version=${TAG}" \
            --tag "docker.io/mcanouil/eggla:${TAG}" \
            --file "inst/setup/Dockerfile" \
            .
