name: Build Docker

on:
  workflow_dispatch:

jobs:
  build-docker-devel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      bake_json: [inst/setup/docker-bake.json]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        run: |
          for itarget in $(jq '.group[].default[].targets[]' -r ${bake_json});
            do docker buildx bake --file ${bake_json} --set=*.labels.org.opencontainers.image.revision=${GITHUB_SHA} --push ${itarget};
          done
