name: Build Docker

on:
  workflow_dispatch:
  workflow_run:
    workflows: "R-CMD-check"
    branches: main
    types: completed
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-docker:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' || 
        github.event_name == 'release' || 
        (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        run: |
          if [[ "${{github.ref_name}}" = "main" ]]; then
            TAG="devel"
            docker buildx build \
              --push \
              --platform "linux/amd64" \
              --tag "ghcr.io/mcanouil/eggla:${TAG}" \
              --file "inst/setup/Dockerfile" \
              --label "org.opencontainers.image.version=" \
              .
          else
            TAG=${{github.ref_name}}
            docker buildx build \
              --push \
              --platform "linux/amd64" \
              --tag "ghcr.io/mcanouil/eggla:${TAG#v}" \
              --tag "ghcr.io/mcanouil/eggla:latest" \
              --file "inst/setup/Dockerfile" \
              --label "org.opencontainers.image.version=${TAG}" \
              .
          fi
          docker container run --rm ghcr.io/mcanouil/eggla:${TAG#v} Rscript eggla-example.R
