name: Build & Test Devcontainer Image

on:
  workflow_dispatch:
  workflow_run:
    workflows: "R-CMD-check"
    branches: main
    types: completed
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-devcontainer:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' || 
        github.event_name == 'release' || 
        (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Build dev container
        run: |
          if [[ "${{github.ref_name}}" = "main" ]]; then
            TAG="devel"
            devcontainer build \
              --config .github/.devcontainer/devcontainer.json \
              --cache-from ghcr.io/${{ github.repository }}:${TAG} \
              --image-name ghcr.io/${{ github.repository }}:${TAG} \
              --push false \
              --workspace-folder . 
          else
            TAG=${{github.ref_name}}
            devcontainer build \
              --config .github/.devcontainer/devcontainer.json \
              --cache-from ghcr.io/${{ github.repository }}:${TAG#v} \
              --image-name ghcr.io/${{ github.repository }}:${TAG#v} \
              --push false \
              --workspace-folder . 
          fi

      - name: Start dev container
        run: |
          if [[ "${{github.ref_name}}" = "main" ]]; then
            TAG="devel"
            devcontainer up \
              --config .github/.devcontainer/devcontainer.json \
              --cache-from ghcr.io/${{ github.repository }}:${TAG} \
              --workspace-folder .
          else
            TAG=${{github.ref_name}}
            devcontainer up \
              --config .github/.devcontainer/devcontainer.json \
              --cache-from ghcr.io/${{ github.repository }}:${TAG#v} \
              --workspace-folder .
          fi

      - name: Run tests in dev container
        run: |
          devcontainer exec \
            --config .github/.devcontainer/devcontainer.json \
            --workspace-folder . \
            Rscript eggla-example.R

      - name: Push dev container
        run: |
          if [[ "${{github.ref_name}}" = "main" ]]; then
            TAG="devel"
            devcontainer build \
              --config .github/.devcontainer/devcontainer.json \
              --cache-from ghcr.io/${{ github.repository }}:${TAG} \
              --image-name ghcr.io/${{ github.repository }}:${TAG} \
              --push true \
              --workspace-folder . 
          else
            TAG=${{github.ref_name}}
            devcontainer build \
              --config .github/.devcontainer/devcontainer.json \
              --cache-from ghcr.io/${{ github.repository }}:${TAG#v} \
              --image-name ghcr.io/${{ github.repository }}:${TAG#v} \
              --push true \
              --workspace-folder . 
          fi
