name: Latest

on:
  workflow_dispatch:

jobs:
  latest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker images to GitHub Container Registry
        run: |
          docker pull ghcr.io/mcanouil/eggla:v0.9.0
          docker tag ghcr.io/mcanouil/eggla:v0.9.0 ghcr.io/mcanouil/eggla:latest
          docker push ghcr.io/mcanouil/eggla:latest
